text_extensions: [ 'coffee', 'css', 'erb', 'haml', 'handlebars', 'hb',
                   'htm', 'html', 'js', 'less', 'markdown', 'md', 'ms',
                   'mustache', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml',
                   'xml' ]

index_filenames: [ 'index.html' ]
output_dir: output
enable_output_diff: true

prune:
  auto_prune: true
  exclude: [ '.git', '.gitkeep', '.hg', '.svn', 'CVS' ]

data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /
    allow_periods_in_identifiers: false

watcher:
  -
   dirs_to_watch: [ 'commands', 'content', 'layouts', 'lib' ]
   files_to_watch: [ 'config.yaml', 'Rules' ]
   notify_on_compilation_success: true
   notify_on_compilation_failure: true
